In [6]:
import numpy as np
x = [60, 65, 70, 62, 75, 78, 67]
mean = np.mean([x])
print(mean)

68.14285714285714


In [1]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.5958, 0.9525, 0.9393],
        [0.3049, 0.0054, 0.6412],
        [0.9880, 0.8680, 0.1544],
        [0.2913, 0.6353, 0.6612],
        [0.2838, 0.2080, 0.5791]])


In [1]:

import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


In [5]:
from scipy import sparse
    # Create a 2D NumPy array with a diagonal of ones, and zeros everywhere else
eye = np.eye(5)
print(eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
